<a href="https://colab.research.google.com/github/Agnik101/ANN_Regression-vs-Multiple-Linear-Regression/blob/main/ANN_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

### Importing the dataset

In [4]:
data=pd.read_excel('/content/Folds5x2_pp.xlsx')
data.head()


AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [5]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [6]:
print(X)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [7]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [10]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1))

### Compiling the ANN

In [15]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 3604.4946
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 118.9173
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 113.8365
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 107.9276
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 101.7441
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 95.0143
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 88.4174
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 81.5451
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 75.3268
Epoch 10/100
240/240 [==============================] - 0s 2ms/step - loss: 68.9022
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 63.5237
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - loss: 58.

### Predicting the results of the Test set

In [17]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 1ms/step
[[428.75 431.23]
 [459.62 460.01]
 [463.07 461.14]
 ...
 [470.35 473.26]
 [437.15 438.  ]
 [456.34 463.28]]


Accuracy of ANN_REGRESSION:

In [21]:
from sklearn.metrics import r2_score
r2_score=r2_score(y_test,y_pred)
print("Accuracy :",r2_score)

Accuracy : 0.8917222748742633
